version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
      - minio
      - livekit
    environment:
      - RUST_LOG=info
      - DATABASE_URL=postgres://postgres:password@postgres/streamrecorder
      - REDIS_URL=redis://redis
      - MINIO_ENDPOINT=http://minio:9000
      - METRICS_ENDPOINT=http://prometheus:9090

  postgres:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: streamrecorder
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    volumes:
      - ./data/redis:/data
    ports:
      - "6379:6379"

  minio:
    image: minio/minio
    command: server /data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - ./data/minio:/data
    ports:
      - "9000:9000"
      - "9001:9001"

  livekit:
    image: livekit/livekit-server
    ports:
      - "7880:7880"
      - "7881:7881"
      - "7882:7882/udp"
    environment:
      - LIVEKIT_KEYS=devkey:secret
      - LIVEKIT_REDIS_HOST=redis

  prometheus:
    image: prom/prometheus:v2.45.0
    volumes:
      - ./docker/prometheus:/etc/prometheus
      - ./data/prometheus:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:10.0.0
    depends_on:
      - prometheus
    ports:
      - "3001:3000"
    volumes:
      - ./docker/grafana/provisioning:/etc/grafana/provisioning
      - ./data/grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_ROOT_URL=http://localhost:3001/grafana

  node-exporter:
    image: prom/node-exporter:v1.6.0
    ports:
      - "9100:9100"

  redis-exporter:
    image: oliver006/redis_exporter:v1.54.0
    environment:
      - REDIS_ADDR=redis://redis:6379
    ports:
      - "9121:9121"

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter:v0.12.0
    environment:
      - DATA_SOURCE_NAME=postgresql://postgres:password@postgres:5432/streamrecorder?sslmode=disable
    ports:
      - "9187:9187"
